FROM ghcr.io/falcon-ifsp/drone-sim/ardupilot:latest

ENV CCACHE_TEMPDIR=/tmp

COPY src/ /ardupilot 
RUN /ardupilot/modules/waf/waf-light configure --board sitl && \
    /ardupilot/modules/waf/waf-light build --target bin/arducopter

RUN sudo rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

EXPOSE 5760/tcp 5762/tcp 5763/tcp
