apiVersion: v1
kind: Pod
metadata:
  name: ardupilot-pod
  labels:
    app: ardupilot-pod
    
spec:
  hostNetwork: true
  volumes:
  - name: ardupilot-source
    hostPath:
      path: /opt/ardupilot
      type: Directory
  - name: xauthority
    hostPath:
      path: /run/user/1000/xauth_mfXDrs
      type: File

  containers:
  - name: sitl
    image: localhost/ardupilot:latest
    args: ["/ardupilot/Tools/autotest/sim_vehicle.py", "-v", "copter", "-f", "quad", "--console"]
    tty: true
    securityContext:
      seLinuxOptions:
        type: spc_t
    env:
    - name: DISPLAY
      value: ":0"
    - name: XAUTHORITY
      value: "/tmp/xauth/xauth_mfXDrs"
    volumeMounts:
    - name: ardupilot-source
      mountPath: /ardupilot:U,Z
    - name: xauthority
      mountPath: /tmp/xauth/xauth_mfXDrs
      readOnly: true
