apiVersion: v1
kind: Pod
metadata:
  name: drone-sim
  labels:
    app: drone-sim.pod
    
spec:
  hostNetwork: true
  volumes:
  - name: ardupilot-source
    hostPath:
      path: /opt/ardupilot
      type: Directory
  - name: xauthority
    hostPath:
      path: /run/user/1000/xauth_OwVQAW
      type: File

  containers:
  - name: gazebo-harmonic
    image: ghcr.io/j-rivero/gazebo:harmonic-full

  - name: ardupilot-sitl
    image: localhost/ardupilot:latest
    args: ["/ardupilot/Tools/autotest/sim_vehicle.py", "-v", "copter", "-f", "quad", "--console"]
    tty: true
    securityContext:
      seLinuxOptions:
        type: spc_t
    env:
    - name: DISPLAY
      value: ":0"
    - name: XAUTHORITY
      value: "/tmp/xauth/xauth_OwVQAW"
    volumeMounts:
    - name: ardupilot-source
      mountPath: /ardupilot:U,Z
    - name: xauthority
      mountPath: /tmp/xauth/xauth_OwVQAW:Z
      readOnly: true
