apiVersion: v1
kind: ConfigMap
metadata:
  name: drone-sim-config
data:
  DISPLAY: ":0"
  XAUTHORITY: "${XAUTHORITY}"
  XDG_RUNTIME_DIR: "/run/user/1000"
  GZ_IP: "127.0.0.1"
  TZ: "America/Sao_Paulo"
---
apiVersion: v1
kind: Pod
metadata:
  name: drone-sim
  labels:
    app: drone-sim.pod

spec:
  hostNetwork: true
  containers:
  - name: gazebo-harmonic
    image: localhost/gazebo-harmonic-amd:latest
    args: ["/usr/bin/gz", "sim", "-v4", "-r", "iris_runway.sdf"]
    ports:
    - containerPort: 5600
      protocol: UDP
    resources:
      limits:
        amd.com/gpu: 1
    securityContext:
      allowPrivilegeEscalation: true
      seLinuxOptions:
        type: spc_t
    envFrom:
    - configMapRef:
        name: drone-sim-config
    volumeMounts:
    - name: gazebo-config
      mountPath: /opt/gz_ws/config:Z
      readOnly: true
    - name: gazebo-models
      mountPath: /opt/gz_ws/models:Z
      readOnly: true
    - name: gazebo-worlds
      mountPath: /opt/gz_ws/worlds:Z
      readOnly: true
    - name: xauthority
      mountPath: "${XAUTHORITY}:z"
      readOnly: true
    - name: gpu-device
      mountPath: /dev/dri
    - name: kfd-device
      mountPath: /dev/kfd

  - name: ardupilot-sitl
    image: localhost/ardupilot-sitl:latest
    args: ["/ardupilot/Tools/autotest/sim_vehicle.py", "-v", "ArduCopter", "-f", "gazebo-iris", "--model", "JSON", "--console", "--no-rebuild"]
    tty: true
    ports:
    - containerPort: 5760
      protocol: TCP
    - containerPort: 5762
      protocol: TCP
    - containerPort: 5763
      protocol: TCP
    - containerPort: 9005
      protocol: UDP
    securityContext:
      seLinuxOptions:
        type: spc_t
    envFrom:
    - configMapRef:
        name: drone-sim-config
    volumeMounts:
    - name: xauthority
      mountPath: "${XAUTHORITY}:z"
      readOnly: true

  volumes:
  - name: gazebo-config
    hostPath:
      path: "${PWD}/gazebo-harmonic/src/config"
      type: Directory
  - name: gazebo-models
    hostPath:
      path: "${PWD}/gazebo-harmonic/src/models"
      type: Directory
  - name: gazebo-worlds
    hostPath:
      path: "${PWD}/gazebo-harmonic/src/worlds"
      type: Directory
  - name: xauthority
    hostPath:
      path: "${XAUTHORITY}"
      type: File
  - name: gpu-device
    hostPath:
      path: /dev/dri
      type: Directory
  - name: kfd-device
    hostPath:
      path: /dev/kfd
      type: Directory