FROM ghcr.io/j-rivero/gazebo:jetty-full

RUN apt-get update && apt-get install -y libgz-sim10-dev rapidjson-dev libopencv-dev \
    libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev gstreamer1.0-plugins-bad \
    gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-gl \
    git cmake build-essential

RUN mkdir -p /opt/gz_ws && git clone https://github.com/ArduPilot/ardupilot_gazebo /opt/gz_ws
ENV GZ_VERSION=jetty \
    GZ_SIM_SYSTEM_PLUGIN_PATH=/opt/gz_ws/build:$GZ_SIM_SYSTEM_PLUGIN_PATH \
    GZ_SIM_RESOURCE_PATH=/opt/gz_ws/models:/opt/gz_ws/worlds:$GZ_SIM_RESOURCE_PATH
RUN cd /opt/gz_ws && mkdir build && cd /opt/gz_ws/build && \
    cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo && make -j$(nproc)

RUN apt-get autoremove -y && apt-get clean -y && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*