apiVersion: v1
kind: ConfigMap
metadata:
  name: gazebo-harmonic-config
data:
  DISPLAY: ":0"
  XAUTHORITY: "${XAUTHORITY}"
  XDG_RUNTIME_DIR: "/run/user/${USER_UID}"
  GZ_IP: "127.0.0.1"
  TZ: "America/Sao_Paulo"
---
apiVersion: v1
kind: Pod
metadata:
  name: gazebo-harmonic
  labels:
    app: gazebo-harmonic.pod

spec:
  hostNetwork: true
  containers:
  - name: main
    image: localhost/gazebo-harmonic-ardupilot:latest
    args: ["/usr/bin/gz", "sim", "-v4", "-r", "iris_runway.sdf"]
    ports:
    - containerPort: 5600
      protocol: UDP
    securityContext:
      allowPrivilegeEscalation: true
      seLinuxOptions:
        type: spc_t
    envFrom:
    - configMapRef:
        name: gazebo-harmonic-config
    volumeMounts:
    - name: gazebo-config
      mountPath: /opt/gz_ws/config:Z
      readOnly: true
    - name: gazebo-models
      mountPath: /opt/gz_ws/models:Z
      readOnly: true
    - name: gazebo-worlds
      mountPath: /opt/gz_ws/worlds:Z
      readOnly: true
    - name: xauthority
      mountPath: "${XAUTHORITY}:z"
      readOnly: true
    - name: gpu-device
      mountPath: /dev/dri

  volumes:
  - name: gazebo-config
    hostPath:
      path: "${PWD}/gazebo-harmonic/src/config"
      type: Directory
  - name: gazebo-models
    hostPath:
      path: "${PWD}/gazebo-harmonic/src/models"
      type: Directory
  - name: gazebo-worlds
    hostPath:
      path: "${PWD}/gazebo-harmonic/src/worlds"
      type: Directory
  - name: xauthority
    hostPath:
      path: "${XAUTHORITY}"
      type: File
  - name: gpu-device
    hostPath:
      path: /dev/dri
      type: Directory
  - name: kfd-device
    hostPath:
      path: /dev/kfd
      type: Directory
