FROM ghcr.io/j-rivero/gazebo:harmonic-full

RUN apt-get update && apt-get upgrade -y && apt-get dist-upgrade -y && \
    apt-get install -y git libqt5svg5 libgz-sim8-dev rapidjson-dev libopencv-dev \
    libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev gstreamer1.0-plugins-bad \
    gstreamer1.0-plugins-good gstreamer1.0-plugins-ugly \
    gstreamer1.0-libav gstreamer1.0-gl libdebuginfod1


RUN curl -o /tmp/amdgpu-install_7.2.70200-1_all.deb \
    https://repo.radeon.com/amdgpu-install/25.35/ubuntu/jammy/amdgpu-install_7.2.70200-1_all.deb && \
    apt-get install -y /tmp/amdgpu-install_7.2.70200-1_all.deb && \
    rm -f /tmp/amdgpu-install_7.2.70200-1_all.deb 

RUN amdgpu-install -y --usecase=graphics

RUN mkdir -p /opt/gz_ws && git clone https://github.com/ArduPilot/ardupilot_gazebo /opt/gz_ws
ENV GZ_VERSION=harmonic \
    GZ_SIM_SYSTEM_PLUGIN_PATH=/opt/gz_ws/build:$GZ_SIM_SYSTEM_PLUGIN_PATH \
    GZ_SIM_RESOURCE_PATH=/opt/gz_ws/models:/opt/gz_ws/worlds:$GZ_SIM_RESOURCE_PATH
RUN cd /opt/gz_ws && mkdir build && cd /opt/gz_ws/build && \
    cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo && make -j$(nproc)

RUN apt-get autoremove -y && apt-get clean -y && \
    rm -rf /var/lib/apt/lists/*