apiVersion: v1
kind: ConfigMap
metadata:
  name: gazebo-harmonic-config
data:
  DISPLAY: ":0"
  XAUTHORITY: "/run/user/1000/xauth_FkJMoe"
  XDG_RUNTIME_DIR: "/run/user/1000"
  GZ_IP: "127.0.0.1"
  TZ: "America/Sao_Paulo"
---
apiVersion: v1
kind: Pod
metadata:
  name: gazebo-harmonic
  labels:
    app: gazebo-harmonic.pod

spec:
  hostNetwork: true
  containers:
  - name: main
    image: localhost/gazebo-harmonic-amd:latest
    args: ["/usr/bin/gz", "sim", "-v4", "-r", "iris_runway.sdf"]
    ports:
    - containerPort: 5600
      protocol: UDP
    resources:
      limits:
        amd.com/gpu: 1
    securityContext:
      allowPrivilegeEscalation: true
      seLinuxOptions:
        type: spc_t
    envFrom:
    - configMapRef:
        name: gazebo-harmonic-config
    volumeMounts:
    - name: xauthority
      mountPath: /run/user/1000/xauth_FkJMoe:Z
      readOnly: true
    - name: gpu-device
      mountPath: /dev/dri
    - name: kfd-device
      mountPath: /dev/kfd

  volumes:
  - name: xauthority
    hostPath:
      path: /run/user/1000/xauth_FkJMoe
      type: File
  - name: gpu-device
    hostPath:
      path: /dev/dri
      type: Directory
  - name: kfd-device
    hostPath:
      path: /dev/kfd
      type: Directory
