apiVersion: v1
kind: ConfigMap
metadata:
  name: ardupilot-config
data:
  DISPLAY: ":0"
  XAUTHORITY: "/tmp/xauth/xauth_FkJMoe"
  TZ: "America/Sao_Paulo"
---
apiVersion: v1
kind: Pod
metadata:
  name: ardupilot
  labels:
    app: ardupilot.pod
    
spec:
  hostNetwork: true
  containers:
  - name: main
    image: localhost/ardupilot-sitl:latest
    args: ["/ardupilot/Tools/autotest/sim_vehicle.py", "-v", "ArduCopter", "-f", "gazebo-iris", "--model", "JSON", "--console"]
    tty: true
    ports:
    - containerPort: 5760
    resources:
      limits:
        amd.com/gpu: 1
    securityContext:
      seLinuxOptions:
        type: spc_t
    envFrom:
    - configMapRef:
        name: ardupilot-config
    volumeMounts:
    - name: xauthority
      mountPath: /run/user/1000/xauth_FkJMoe:Z
      readOnly: true
    - name: gpu-device
      mountPath: /dev/dri

  volumes:
  - name: ardupilot-source
    hostPath:
      path: /opt/ardupilot
      type: Directory
  - name: xauthority
    hostPath:
      path: /run/user/1000
      type: Directory
